# -*- coding: utf-8 -*-
"""labyrinth (4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Biedtf1n5i53R8d4iEhFTEloczLdqU5M
"""

f = open("labirint.txt", "r")

field = []
for line in f:
    field.append(list(line.strip()))
f.close()

start_coords = []
for i in range(len(field)):
    for j in range(len(field[0])):
        if field[i][j] == '$':
            start_coords.append([i, j])

flags = []

for [x_i, x_j] in start_coords:
    x_i += 1
    flag = []
    stack = []
    while field[x_i][x_j] != '@':
        if (field[x_i][x_j] == '('):
            i = 1
            number = []
            a_char = stack.pop()
            flag.insert(0, a_char)
            while (field[x_i][x_j + i].isdigit()):
                number.append(field[x_i][x_j + i])
                i += 1
            x_j -= int("".join(number))
            continue
        if (field[x_i][x_j] == ')'):
            i = 1
            number = []
            a_char = stack.pop()
            flag.append(a_char)
            while (field[x_i][x_j - i].isdigit()):
                number.append(field[x_i][x_j - i])
                i += 1
            x_j += int("".join(number))
            continue
        if (field[x_i][x_j] == '-'):
            i = 1
            number = []        
            flag = flag[1:]
            while (field[x_i + i][x_j].isdigit()):
                number.append(field[x_i + i][x_j])
                i += 1
            x_i -= int("".join(number))
            continue
        if (field[x_i][x_j] == '+'):
            i = 1
            number = []        
            flag = flag[:-1]
            while (field[x_i - i][x_j].isdigit()):
                number.append(field[x_i - i][x_j])
                i += 1
            x_i += int("".join(number))
            continue
        if (field[x_i][x_j] == '%'):      
            flag = flag[::-1]
            x_i += 1
            continue
        if (field[x_i][x_j] == '['):      
            stack.append(field[x_i][x_j + 1])
            x_j += 2
            continue
        if (field[x_i][x_j] == ']'):      
            stack.append(field[x_i][x_j - 1])
            x_j -= 2
            continue
        if (field[x_i][x_j] == '*'):      
            stack.append(field[x_i - 1][x_j])
            x_i -= 2
            continue
        if (field[x_i][x_j] == '.'):      
            stack.append(field[x_i + 1][x_j])
            x_i += 2
            continue
        if (field[x_i][x_j] == '$'):      
            x_i += 1
            continue
        if (field[x_i][x_j] == '<'):      
            i = 1
            number = []        
            while (field[x_i][x_j + i].isdigit()):
                number.append(field[x_i][x_j + i])
                i += 1
            x_j -= int("".join(number))
            continue
        if (field[x_i][x_j] == '>'):      
            i = 1
            number = []        
            while (field[x_i][x_j - i].isdigit()):
                number.append(field[x_i][x_j - i])
                i += 1
            x_j += int("".join(number))
            continue
        if (field[x_i][x_j] == '^'):      
            i = 1
            number = []        
            while (field[x_i + i][x_j].isdigit()):
                number.append(field[x_i + i][x_j])
                i += 1
            x_i -= int("".join(number))
            continue
        if (field[x_i][x_j] == 'v'):      
            i = 1
            number = []        
            while (field[x_i - i][x_j].isdigit()):
                number.append(field[x_i - i][x_j])
                i += 1
            x_i += int("".join(number))
            continue
        if (field[x_i][x_j] == '#'):
            print("ALERT!")
            flag = []
            break
    if (flag != []):
        flags.append(flag)

new_flags = []
for flag in flags:
    new_flags.append("".join(flag))

for flag in new_flags:
    if "{FLG:" in flag:
        key = flag

