# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10IFkFiKq9pQvGPCGdqmoq3kRga9QSyuk
"""

array = [1, 1, 4, 8, 9, 2, 4, 8, 44, 5, 86, 2, 4, 0]
new_array = []

interrupt = 0
cnt = 0
prev_diff = array[1] - array[0]
for i in range(1, len(array) - 1):
  diff = array[i+1] - array[i]
  if (prev_diff*diff >= 0 and array[i+1]!=0):
    prev_diff = diff
    continue
  else:
    if (prev_diff > 0):
      cnt += 1
    subarray = array[interrupt:i+1]
    for item in subarray[::-1]:
      new_array.append(item)
    prev_diff = diff
    if (prev_diff > 0):
      interrupt = i
    elif (prev_diff < 0):
      interrupt = i + 2

new_array.append(cnt)

